/**
 * @file search.types.ts
 * MD3 Expressive Search — TypeScript prop definitions.
 * Spec: https://m3.material.io/components/search/overview
 * Reference: docs/m3/search/SearchBar.kt (MD3 Expressive)
 */

import type * as React from "react";

// ─── Variant & Style ──────────────────────────────────────────────────────────

/**
 * Display variant for the expanded SearchView.
 *
 * - `docked`: Popup dropdown below the SearchBar. For medium/large screens.
 * - `fullscreen`: Full-screen dialog overlay. For compact/mobile screens.
 */
export type SearchVariant = "docked" | "fullscreen";

/**
 * Visual style type for the SearchView.
 *
 * - `contained`: No divider between the input area and results.
 *   The container background is preserved continuously (recommended).
 * - `divided`: A HorizontalDivider separates the input area from results.
 */
export type SearchStyleType = "contained" | "divided";

// ─── Internal Shared Props ────────────────────────────────────────────────────

/**
 * Internal props shared between SearchBar and SearchView sub-components.
 * Not part of the public API.
 * @internal
 */
export interface SearchInternalProps {
	/** Unique ID generated by useId(), used as Framer Motion layoutId. */
	searchId: string;
	/** Unique ID for the results listbox, used for aria-controls. */
	listboxId: string;
}

// ─── Public API ────────────────────────────────────────────────────────────────

/**
 * Props for the `<Search>` component (orchestrator).
 *
 * @example
 * ```tsx
 * const [query, setQuery] = useState("");
 * const [active, setActive] = useState(false);
 *
 * <Search
 *   query={query}
 *   onQueryChange={setQuery}
 *   onSearch={(q) => console.log("search:", q)}
 *   active={active}
 *   onActiveChange={setActive}
 *   variant="docked"
 *   styleType="contained"
 * >
 *   <SearchResultsList />
 * </Search>
 * ```
 */
export interface SearchProps {
	// ── State ─────────────────────────────────────────────────────────────
	/** Current search query value (controlled). */
	query: string;
	/** Called when user types in the search input. */
	onQueryChange: (query: string) => void;
	/** Called when user submits search (Enter key or suggestion click). */
	onSearch: (query: string) => void;
	/** Whether the SearchView is expanded/open (controlled). */
	active: boolean;
	/** Called when the Search open/close state should change. */
	onActiveChange: (active: boolean) => void;

	// ── Variants ──────────────────────────────────────────────────────────
	/**
	 * Display variant for the expanded state.
	 * @default "docked"
	 */
	variant?: SearchVariant;
	/**
	 * Visual style for the SearchView container.
	 * @default "contained"
	 */
	styleType?: SearchStyleType;
	/**
	 * Whether to add a 2dp gap between the input header and the results list.
	 * Only applies when `variant="docked"`.
	 * @default false
	 */
	hasGap?: boolean;

	// ── Content ───────────────────────────────────────────────────────────
	/**
	 * Icon rendered at the leading edge of the search input.
	 * Defaults to a built-in search icon.
	 */
	leadingIcon?: React.ReactNode;
	/**
	 * Icon or action rendered at the trailing edge of the search input.
	 * Common examples: mic, camera, QR code.
	 */
	trailingIcon?: React.ReactNode;
	/** Placeholder text shown when the input is empty. @default "Search" */
	placeholder?: string;
	/**
	 * Align the placeholder text to left, center, or right.
	 * Typed text will always remain left-aligned.
	 * @default "left"
	 */
	textAlign?: "left" | "center" | "right";
	/**
	 * Search results or suggestions rendered inside the SearchView.
	 * Use `role="option"` on each item for accessibility.
	 */
	children?: React.ReactNode;

	// ── Accessibility ──────────────────────────────────────────────────────
	/**
	 * Override the auto-generated input element ID.
	 * Auto-generated via React.useId() if not provided.
	 */
	id?: string;
	/**
	 * Accessible label for the search landmark.
	 * @default "Search"
	 */
	"aria-label"?: string;

	// ── Styling ────────────────────────────────────────────────────────────
	/** Additional CSS classes for the SearchBar root element. */
	className?: string;
	/** Additional CSS classes for the SearchView container. */
	viewClassName?: string;
}

// ─── Hook Return ───────────────────────────────────────────────────────────────

/**
 * Return type for `useSearchKeyboard`.
 * @internal
 */
export interface UseSearchKeyboardReturn {
	/** Currently highlighted suggestion index. -1 = none. */
	activeIndex: number;
	/** KeyDown handler — attach to the search input. */
	handleKeyDown: (e: React.KeyboardEvent) => void;
	/** Reset activeIndex (e.g., when query changes). */
	resetActiveIndex: () => void;
}
